<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="8.0.5" />
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="itext7.pdfhtml" Version="5.0.5" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DatabaseHelper.cs">
      <Generator>MSBuild:Compile</Generator>
    </Compile>
  </ItemGroup>

</Project>
